# Generated by Django 5.1.7 on 2025-03-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_active_course_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
