# Generated by Django 5.1.7 on 2025-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
