# Generated by Django 5.1.7 on 2025-03-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
    ]
