# Generated by Django 5.1.7 on 2025-03-12 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_options'),
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainee',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='name',
        ),
        migrations.AddField(
            model_name='trainee',
            name='assigned_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainee',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "01XXXXXXXXX". Up to 11 digits allowed.', regex='^01[0-2,5]{1}[0-9]{8}$')]),
        ),
    ]
