# Generated by Django 5.1.7 on 2025-03-14 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_alter_trainee_options_remove_trainee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "01XXXXXXXXX". Up to 11 digits allowed.', regex='^01[0-2,5]{1}[0-9]{8}$')]),
        ),
    ]
