# Generated by Django 5.1.7 on 2025-03-18 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_options'),
        ('trainee', '0003_alter_trainee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='assigned_course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='course.course'),
            preserve_default=False,
        ),
    ]
